//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UITests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UITests.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;DictionaryProxyOfStringObject xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;KeysAndValues&gt;
        ///    &lt;Key&gt;LoggingLevel&lt;/Key&gt;
        ///    &lt;Value xsi:type=&quot;xsd:string&quot;&gt;WARN&lt;/Value&gt;
        ///  &lt;/KeysAndValues&gt;
        ///  &lt;KeysAndValues&gt;
        ///    &lt;Key&gt;BaseUrl&lt;/Key&gt;
        ///    &lt;Value xsi:type=&quot;xsd:string&quot;&gt;&lt;/Value&gt;
        ///  &lt;/KeysAndValues&gt;
        ///  &lt;KeysAndValues&gt;
        ///    &lt;Key&gt;CopyEmailsWhenFiling&lt;/Key&gt;
        ///    &lt;Value xsi:type=&quot;xsd:boolean&quot;&gt;true&lt;/Value&gt;
        ///  &lt;/KeysAndValu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CompanionConfig {
            get {
                return ResourceManager.GetString("CompanionConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///    {
        ///        &quot;_id&quot;: &quot;1&quot;,
        ///        &quot;_type&quot;: &quot;Matter&quot;,
        ///        &quot;_metadataId&quot;: 193,
        ///        &quot;name&quot;: &quot;QA1&quot;,
        ///        &quot;matterNumber&quot;: &quot;MAT-1&quot;,
        ///        &quot;primaryMatterType&quot;: &quot;Contracts&quot;,
        ///        &quot;openDate&quot;: &quot;08/29/2018&quot;,
        ///        &quot;matterStatus&quot;: &quot;Open&quot;,
        ///        &quot;primaryInternalPerson_fullName&quot;: &quot;brown sally&quot;,
        ///        &quot;closeDate&quot;: &quot;&quot;,
        ///        &quot;practiceAreaBusinessUnit&quot;: &quot;OC-OC&quot;,
        ///        &quot;spendToDate&quot;: &quot;0.00 USD&quot;,
        ///        &quot;matterStatus_code&quot;: &quot;Open&quot;,
        ///        &quot;matterStatusCalc&quot;: &quot;Open - 08/29/2018&quot;,
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FavoriteMatters {
            get {
                return ResourceManager.GetString("FavoriteMatters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory and CPU Utilization Report.
        /// </summary>
        internal static string MemoryAndCpuReportTitle {
            get {
                return ResourceManager.GetString("MemoryAndCpuReportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in to Office Companion
        ///Open e-mail inspector window
        ///Expand the Office Companion
        ///Wait for the Office Companion to load plus two seconds
        ///Repeat steps 2-4, {n} times
        ///Close all inspector windows.
        /// </summary>
        internal static string open_and_expand_n_inspector_windows_without_closing {
            get {
                return ResourceManager.GetString("open_and_expand_n_inspector_windows_without_closing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in to Office Companion
        ///Open e-mail inspector window
        ///Expand the Office Companion
        ///Wait for the Office Companion to load plus two seconds
        ///Close inspector window
        ///Repeat steps 2-5, {n} times.
        /// </summary>
        internal static string open_expand_and_close_n_inspector_windows {
            get {
                return ResourceManager.GetString("open_expand_and_close_n_inspector_windows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in to Office Companion
        ///Open matters tab
        ///Open spend tab
        ///Repeat steps 2-3, {n} times.
        /// </summary>
        internal static string reload_invoice_list {
            get {
                return ResourceManager.GetString("reload_invoice_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in to Office Companion
        ///Open all matters tab
        ///Open favorites list
        ///Repeat steps 2-3, {n} times.
        /// </summary>
        internal static string reload_matter_list {
            get {
                return ResourceManager.GetString("reload_matter_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in to Office Companion
        ///Open matter emails tab
        ///Open matter documents tab
        ///Open matter narratives tab
        ///Open matter people tab
        ///Open matter tasks/events tab
        ///Repeat steps 2-6, {n} times.
        /// </summary>
        internal static string reload_matter_summary_tabs {
            get {
                return ResourceManager.GetString("reload_matter_summary_tabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;&lt;style type=&quot;text/css&quot;&gt;
        ///        body {
        ///            font-family: &quot;Times New Roman&quot;;
        ///            font-size: 14px;
        ///            padding: 0.2in 0.3in;
        ///        }
        ///        h1 {
        ///            font-size: 18px;
        ///        }
        ///        h2 {
        ///            font-size: 16px;
        ///        }
        ///        h3 {
        ///            font-style: italic;
        ///            font-size: 16px;
        ///            font-weight: normal;
        ///        }
        ///        table, div, img  {
        ///           [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReportTemplate {
            get {
                return ResourceManager.GetString("ReportTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in to Office Companion
        ///Open spend tab
        ///Scroll to bottom of the list of 500 invoices.
        /// </summary>
        internal static string scroll_invoice_list {
            get {
                return ResourceManager.GetString("scroll_invoice_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in to Office Companion
        ///Open matters tab
        ///Scroll to bottom of the list of 500 matters.
        /// </summary>
        internal static string scroll_matter_list {
            get {
                return ResourceManager.GetString("scroll_matter_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Populate test emails folder with {n} messages
        ///Log in to Office Companion
        ///Open first matter in list
        ///Open test emails folder and select all messages
        ///Drag all selected messages to opened matter.
        /// </summary>
        internal static string upload_n_emails_at_once {
            get {
                return ResourceManager.GetString("upload_n_emails_at_once", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Populate test emails folder with {n} messages
        ///Log in to Office Companion
        ///Open first matter in list
        ///Open test emails folder and select first (or next) email
        ///Drag email opened matter
        ///Repeat steps 3-5, {n} times.
        /// </summary>
        internal static string upload_n_emails_one_at_a_time {
            get {
                return ResourceManager.GetString("upload_n_emails_one_at_a_time", resourceCulture);
            }
        }
    }
}
